### ISSUE TITLE
Test Installation

### ISSUE THREAD

**Issue by skreutzberger** [SwiftyBeaver/AES256CBC#1]
@davidrothera Can you please do your build check magic on this project before I announce it to the world? Cocoapods should work but I can not really test Carthage and Swift Package Manager.

Maybe you also spot other issues with the release :)

Thanks!

**Comment by davidrothera** [comment]
Will do, I will get round to this later and let you know :+1:

**Comment by davidrothera** [comment]
SPM works fine

**Comment by davidrothera** [comment]
Added 2 PR's

* Added and tested adding to Swift PM
* Removed and added new Framework targets for watchOS, tvOS and OSX and tested that these all compile with Carthage

**Comment by davidrothera** [comment]
You will need to push a new tag for SPM to work (heads-up) :rocket:

**Comment by skreutzberger** [comment]
I pushed the tag and now I could already successfully test Carthage for a Mac OS X app.

![excited](https://cloud.githubusercontent.com/assets/564725/13961090/5e196900-f05b-11e5-8a21-f63db1c9a689.gif)
