### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by yoonjason** [SwiftyBeaver/AES256CBC#10]
hello
` let email = self.emailTextField.text!
        let pass = self.passTextField.text!
        let data : String = AES256CBC.encryptString(email, password: pass)!
        print(data)
`
self.emailTextField.text and self.passTextField.text data is 123

fatal error: unexpectedly found nil while unwrapping an Optional value

why?..

**Comment by skreutzberger** [comment]
That happens because you force unwrap an optional which results in a crash in Swift :) 

use `guard` or check if `nil` to avoid that issue.
