### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by bull-xu-stride** [SwiftyBeaver/AES256CBC#12]
The line 196 `return String(data: dec, encoding: String.Encoding.utf8)! ` is nil but using ! to return the wrapped value causing crash.

    fileprivate class func aesDecrypt(_ str: String, key: String, iv: String) throws -> String {
        let keyData = key.data(using: String.Encoding.utf8)!
        let ivData = iv.data(using: String.Encoding.utf8)!
        //let data = Data(base64Encoded: str, options: NSData.Base64DecodingOptions(rawValue: 0))!
        let data = Data(base64Encoded: str)!
        let dec = try Data(bytes: AESCipher(key: keyData.bytes,
                                            iv: ivData.bytes).decrypt(bytes: data.bytes))
        return String(data: dec, encoding: String.Encoding.utf8)!
    }

We should always avoid using ! to access the wrapped value for optional types.

**Comment by skreutzberger** [comment]
you are absolutely right! I am actually just now packaging a new version which includes the following fix https://github.com/SwiftyBeaver/AES256CBC/pull/11

**Comment by skreutzberger** [comment]
fixed by today’s 1.2.0 release 🎉

**Comment by bull-xu-stride** [comment]
Very well done @skreutzberger and very quick reply and fix! And you are doing a great job of this project.

**Comment by skreutzberger** [comment]
Thanks!
