### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by yoonjason** [SwiftyBeaver/AES256CBC#13]
I want to use next code
I'm generate iv16Key

Next
` public class func decryptString(_ str: String, password: String, iv16:Stirng) -> String? {
        if str.characters.count > 16 && password.characters.count == 32 {
            // get AES initialization vector from first 16 chars
            let encryptedString = str.replacingOccurrences(of:  iv16, with: "",
                                                           options: String.CompareOptions.literal, range: nil) // remove IV   
            guard let decryptedString = try? aesDecrypt(encryptedString, key: password, iv:  iv16) else {
                print("an error occured while decrypting")
                return nil
            }
            return decryptedString
        }
        return nil
    }`

i custom code is Next
`
public class func decryptString(_ str: String, key32: String, iv16: String) -> String? {     
            guard let decryptedString = try? aesDecrypt(str, key: key32, iv: iv16) else {
                print("an error occured while decrypting")
                return nil
            }
            return decryptedString
    }
`
an error occured while decrypting
fatal error: unexpectedly found nil while unwrapping an Optional value

how to use custom generatekey iv used?

**Comment by skreutzberger** [comment]
Did you try the latest version? It was released 10 days ago.

**Comment by KimiChiu** [comment]
Can't update to 1.2.0 with CocoaPods.

**Comment by skreutzberger** [comment]
ah it seems that CocoaPods does not have the latest version, yet. I will ping you when it is updated.

**Comment by skreutzberger** [comment]
I am experiencing issues updating the CocoaPods registry with some very weird Ruby errors. I try to fix it asap.
