### ISSUE TITLE
openssl_decrypt() PHP doesn't works with Swift AES256CBC

### ISSUE THREAD

**Issue by goutfeb** [SwiftyBeaver/AES256CBC#14]
Hi !

I'm currently working on network exchanges with AES 256 CBC cipher. I'm using your system to crypt my data and openssl_decrypt() to decrypt the data in PHP but that return me empty string.

I checked datas and Key, vector and ciphered data are the same on both sides.

I missed something ?

`openssl_decrypt($data, "AES-256-CBC", $key, 1, $vector;` : PHP side
`AES256CBC.encryptString(swiftData, password: swiftKey, iv: swiftVector))` : Swift side

with : 
$data = swiftData
$key = swiftKey
$vector = $swiftVector
(I made diff on them)

**Comment by skreutzberger** [comment]
if the data is the same then the result should be the same, very uncommon. Can you maybe try it with another library?

**Comment by goutfeb** [comment]
I'll try another lib, but I read somewhere that can be a padding error. And I don't know what kind of padding errors can happen between Swift and PHP

**Comment by skreutzberger** [comment]
If padding is necessary then PKCS7 padding is used. Maybe that already helps a bit.

**Comment by goutfeb** [comment]
Humm... I don't think PHP uses PKCS7 padding. I'll try to add another padding manually Swift side or change something PHP side.

**Comment by goutfeb** [comment]
Do you know a cipher library compatible with PHP openSSL

**Comment by jokechat** [comment]
this is my php code,it is work
```php
        $str       = "9OLqdfG0tP6d0P43amdBFrtDuoM5IPTE2cmedWRV.......";
        $key      = "qgQbrA4psxzgManlfe0cf1jxry9p2c07";
        $iv         = substr($str,0,16);
        $str       = str_replace($iv,'',$str);
        $str       = base64_decode($str);
        $result   = openssl_decrypt($str,"AES-256-CBC", $key,1,$iv);
        $result   = json_decode($result,true);
        var_dump($result);
```
