### ISSUE TITLE
Swift 4 – Xcode 9 Beta 6 Issue

### ISSUE THREAD

**Issue by BryanMorfe** [SwiftyBeaver/AES256CBC#20]
The constructor `extendingOrTruncating` of UInt8 no longer works on the latest release of Swift and Xcode 9 beta 6. Here are some pictures:

<img width="1120" alt="screen shot 2017-08-23 at 11 37 34 am" src="https://user-images.githubusercontent.com/14911936/29624651-a4dd8350-87f7-11e7-9f93-0ebf34ad144c.png">

<img width="1139" alt="screen shot 2017-08-23 at 11 37 52 am" src="https://user-images.githubusercontent.com/14911936/29624654-a6b13014-87f7-11e7-8e82-5b562295c476.png">

**Comment by skreutzberger** [comment]
thanks for reporting! Do you know of a simple fix? Maybe they renamed it?

**Comment by skreutzberger** [comment]
oh and you tried the latest version of the library, right?

**Comment by BryanMorfe** [comment]
I am using the latest version. So far, I have removed the label and it’s not complaining. I will do a few tests and see if it works. I will be reporting back. Thanks!

**Comment by BryanMorfe** [comment]
Reporting back: Removing the label didn't work as I suspected. It throws a fatal error saying that there aren't enough bits to represent a signed value. I will do some reach and will try some more options and I will report back.

**Comment by BryanMorfe** [comment]
Fixed it! I tried the original name for swift 3 and below `truncatingBitPattern` and the compiler itself told it was renamed to `truncatingIfNeeded`. That gets rid of the issue and encrypts and decrypts perfectly fine. Thanks again for the awesome library!

**Comment by BryanMorfe** [comment]
Issue closed.

**Comment by skreutzberger** [comment]
We released today a hotfix for AES256CBC 1.3.0 which should fix the issue in Swift 4: 
https://github.com/SwiftyBeaver/AES256CBC/commit/ad2c4cc3fa415c0b56b92834d3e0fe67f8bd1007

Thanks again for reporting and helping!
