### ISSUE TITLE
Expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions

### ISSUE THREAD

**Issue by bojanm7** [SwiftyBeaver/AES256CBC#22]
Hello,

Use Xcode version 9 beta 6, Swift 3. When try to build my project get this error: "**Expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions**".

Those errors are here (in _AES256CBC.swift_):

<img width="701" alt="screen shot 2017-09-11 at 17 36 51" src="https://user-images.githubusercontent.com/8371532/30283275-ee231e9c-9717-11e7-834d-b412f2bbdbd3.png">

Thanks,

Bojan

**Comment by skreutzberger** [comment]
This issue is resolved in the latest version.

**Comment by mataspetrikas** [comment]
@skreutzberger when is the 1.3.0 planned to be published on the CocoaPods? 
currently I can see there only 1.2.1: https://cocoapods.org/?q=AES256CBC

**Comment by mataspetrikas** [comment]
@skreutzberger when is the 1.3.0 planned to be published on the CocoaPods? 
currently I can see there only 1.2.1: https://cocoapods.org/?q=AES256CBC

**Comment by skreutzberger** [comment]
Sorry, Cocoapods was forgotten. I updated now the Podspec and informed Cocoapods about the new 1.3.0 version. It should be available in some minutes.

**Comment by mataspetrikas** [comment]
@skreutzberger thank you!

**Comment by bojanm7** [comment]
Thanks!
