### ISSUE TITLE
deinitialize and deallocate(capacity:) deprecated

### ISSUE THREAD

**Issue by Hacoga** [SwiftyBeaver/AES256CBC#30]
**deinitialize and deallocate(capacity:) deprecated**
Swift version 5.0
In the class AES256CBC.swift, there is the error. line 915, 916

I have fixed but I don´t sure if I´m correct.

`private func arrayOfBytes<T>(value: T, length: Int? = nil) -> Array<UInt8> {
    let totalBytes = length ?? MemoryLayout<T>.size

    let valuePointer = UnsafeMutablePointer<T>.allocate(capacity: 1)
    valuePointer.pointee = value

    let bytesPointer = UnsafeMutablePointer<UInt8>(OpaquePointer(valuePointer))
    var bytes = Array<UInt8>(repeating: 0, count: totalBytes)
    for j in 0..<min(MemoryLayout<T>.size, totalBytes) {
        bytes[totalBytes - 1 - j] = (bytesPointer + j).pointee
    }

    valuePointer.deinitialize(count: 1)
    valuePointer.deallocate()

    return bytes
 }`

**Comment by skreutzberger** [comment]
Can you please create a pull request? As long as the unit tests are fine (so the decrypted value is the same as the one before the encryption) all should be fine :D

**Comment by skreutzberger** [comment]
Today the new version 1.4.0 was released which adds support for Swift 5, iOS 13 and Xcode 11.
