### ISSUE TITLE
seems broke in latest xcode with swift 5

### ISSUE THREAD

**Issue by PotterDai** [SwiftyBeaver/AES256CBC#31]

**Comment by FontaineDenton** [comment]
Same issue, upgrading to xcode 10.2 and swift 5 breaks this when I try and update carthage dependency. Any plans to fix it?

**Comment by skreutzberger** [comment]
@lgaches do you have a hint what could fix that? I think you did a fix for SwiftyBeaver, too. Thanks!

**Comment by skreutzberger** [comment]
@FontaineDenton Laurent's latest PR https://github.com/SwiftyBeaver/AES256CBC/pull/33 solved the issue.
