### ISSUE TITLE
Swift 5 support

### ISSUE THREAD

**Issue by pablonosh** [SwiftyBeaver/AES256CBC#34]
Hi

Can you guys update the project to support swift 5?

**Comment by skreutzberger** [comment]
Feel free to send a PR :)

**Comment by pablonosh** [comment]
can I get permission to push a branch?

**Comment by skreutzberger** [comment]
You can send a pull request and then it gets merged

**Comment by skreutzberger** [comment]
Today the new version 1.4.0 was released which adds support for Swift 5, iOS 13 and Xcode 11.
