### ISSUE TITLE
return nil

### ISSUE THREAD

**Issue by miadparizadian** [SwiftyBeaver/AES256CBC#37]
String(data: dec, encoding: String.Encoding.utf8) return nil

when dec size of big
how to fix theme?

**Comment by skreutzberger** [comment]
How big is your data and what Swift version are you using?

**Comment by miadparizadian** [comment]
> How big is your data and what Swift version are you using?

my data is 40800 byte
in iphone x is ok but in iphone 5 return nil

**Comment by skreutzberger** [comment]
Ah interesting. So it seems to be a memory issue or CPU issue of a older phones. Encryption is pretty CPU intensive so that may be the reason. Since it is working on an iPhone X I am closing the ticket for now.

**Comment by miadparizadian** [comment]
> Ah interesting. So it seems to be a memory issue or CPU issue of a older phones. Encryption is pretty CPU intensive so that may be the reason. Since it is working on an iPhone X I am closing the ticket for now.

How can I solve this???

**Comment by skreutzberger** [comment]
It seems you can't since it is a limitation of the device's capacity.

**Comment by miadparizadian** [comment]
> It seems you can't since it is a limitation of the device's capacity.

tnx
