### ISSUE TITLE
bug in iphone 5

### ISSUE THREAD

**Issue by miadparizadian** [SwiftyBeaver/AES256CBC#38]
hi
im using aes 256 cbc in iphone 5 (ios 10.3)
but encryption has been problem
3 is right up to the first encryption and others wrong
how to fix theme????!!!!!!
this is fource

**Comment by skreutzberger** [comment]
Is the issue just happening also on a later iPhone? Because there was a similar report some weeks ago about iPhone 5. The iPhone 5 is often too underpowered to be able to do heavy encryption of long strings.
