### ISSUE TITLE
How can we use your library with PBKDF2WithHmacSHA256 key .

### ISSUE THREAD

**Issue by BKudale** [SwiftyBeaver/AES256CBC#39]
Following is equivalent android code
import android.util.Base64
import android.util.Log
import javax.crypto.Cipher
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.IvParameterSpec
import javax.crypto.spec.PBEKeySpec
import javax.crypto.spec.SecretKeySpec

object KeyStoreHelper {
    private const val secretKey: String = "XXxxXXxxXX"
    private const val salt: String = "YyYyYy"

    fun encrypt(strToEncrypt: String): String? {
        try {
            val iv = byteArrayOf(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
            val ivSpec = IvParameterSpec(iv)
            val factory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256")
            val spec = PBEKeySpec(secretKey.toCharArray(), salt.toByteArray(), 65536, 256)
            val tmp = factory.generateSecret(spec)
            val secretKey = SecretKeySpec(tmp.encoded, "AES")
            Log.d("KEY", "tmp==$tmp")
            Log.d("KEY", "secretKey==$secretKey")
            val cipher = Cipher.getInstance("AES/CBC/PKCS5Padding")
            cipher.init(Cipher.ENCRYPT_MODE, secretKey, ivSpec)
            return Base64.encodeToString(cipher.doFinal(strToEncrypt.toByteArray()), Base64.DEFAULT)

        } catch (e: Exception) {
            println("Error while encrypting: $e")
        }

        return null
    }

    fun decrypt(strToDecrypt: String): String? {
        try {
            val iv = byteArrayOf(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
            val ivSpec = IvParameterSpec(iv)
            val factory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256")
            val spec = PBEKeySpec(secretKey.toCharArray(), salt.toByteArray(), 65536, 256)
            val tmp = factory.generateSecret(spec)
            val secretKey = SecretKeySpec(tmp.encoded, "AES")

            val cipher = Cipher.getInstance("AES/CBC/PKCS5PADDING")
            cipher.init(Cipher.DECRYPT_MODE, secretKey, ivSpec)
            return String(cipher.doFinal(Base64.decode(strToDecrypt, Base64.DEFAULT)))
        } catch (e: Exception) {
            println("Error while decrypting: $e")
        }

        return null
    }
}

**Comment by skreutzberger** [comment]
I do not know how the integration works with other libs. The encryption is using a standard AES256CBC with padding and feel free to browse the source code to learn more.
