### ISSUE TITLE
32 bit Archive Bug

### ISSUE THREAD

**Issue by brentatresultstack** [SwiftyBeaver/AES256CBC#40]
Within the last month or two I have had some users report a strange bug around encryption with this library.  When digging into it a bit more it appears that this issue only effects 32 bit devices, so for my application this includes iPhone 5 and iPhone 5c.  In addition this only happens when archiving the application with AES256CBC as a dependency(CocoaPods in my case).  I've never been able to reproduce it when the debugger is attached.

When tracing this issue it is coming from the "F1" function within AESCipher.  The only way I've been able to get a working build for 32 bit devices was to break up the 3rd and 4th "|=" statements into individual variables then NSLog the variables.  When I remove the NSLogs the build outputs incorrect encryption strings.

In my case I'm only encrypting 40 characters and even when I reduce the amount I'm encrypting say to 16 characters the encryption still produces incorrect output.

I have yet to check out the assembly and see what is being outputted by the compiler to see if I can identify what exactly is going on.  I have tried setting the optimization levels to none and that doesn't seem to effect the issue.

As far as I can tell this isn't a bug within the code of this repo, more so a compiler bug that occurs with this repository.  So I'm filing this to ensure that other people are aware of the issue and to bring this to more peoples attention in case someone else has a good idea on how to fix it or work around it.

I'll update this report as I learn more.

**Comment by skreutzberger** [comment]
Thanks for the investigation! We had several complaints by iPhone 5 users and I thought that these were just too slow or so.

**Comment by brentatresultstack** [comment]
Happy to help!

Some good news to report.  After some more testing and installing the latest xCode(11.3) I am no longer able to reproduce the problem on the effected devices.

I am still able to reproduce it still on xCode 11.1.  So there must have been some sort of bug with the compiler between these two versions.

For those stuck on xCode 11.1 or on a version this is happening on here is the full function that I was able to use to fix the issue:

`    fileprivate func F1(_ x0: UInt32, _ x1: UInt32, _ x2: UInt32, _ x3: UInt32) -> UInt32 {
        var result: UInt32 = 0
        result |= UInt32(B1(T0[Int(x0 & 255)]))
        result |= (UInt32(B1(T0[Int((x1 >> 8) & 255)])) << 8)
        // There is an issue with compiling this code for 32 bit devices
        // https://github.com/SwiftyBeaver/AES256CBC/issues/40
        // It's providing invalid ouput when encrypting strings
        // This has only been reproduced on iPhone 5 + 5c
        #if (arch(i386) || arch(arm))
            // 32-bit systems
            result |= (UInt32(B1(T0[Int((x2 >> 16) & 255)])) << 16)
//            result |= (UInt32(B1(T0[Int(x3 >> 24)])) << 24)
            let index4 = Int(x3 >> 24)
            NSLog("\(index4)")
            let T04 = T0[index4]
            let B14 = B1(T04)
            let B14casted = UInt32(B14)
            let shifted4 = B14casted << 24
            result |= shifted4
        #else
            // 64-bit systems
            result |= (UInt32(B1(T0[Int((x2 >> 16) & 255)])) << 16)
            result |= (UInt32(B1(T0[Int(x3 >> 24)])) << 24)
        #endif
        return result
    }`

I am not able to explain why this fixes the issue on xCode 11.1, but since 11.3 fixes the issue I'm going to mark this as closed.  My only suggestion at this point is we put a note in the readme until xCode 11.1 becomes stale/out of date.

Thank you @skreutzberger for providing this repository!
