### ISSUE TITLE
Suggestion/Feature request

### ISSUE THREAD

**Issue by EliteTechnicalCare** [SwiftyBeaver/AES256CBC#41]
Currently decrypt string returns an optional String and will nil out if it isn't encrypted/incorrectly encrypted. A better option would be to make it return the original string, or perhaps have a variable to allow the option to return the original string in the event of failure.

I basically did this:
```

public class func decryptString(_ str: String, password: String) -> String {
        if str.length > 16 && password.length == 32 {
            // get AES initialization vector from first 16 chars
            let iv = String(str.prefix(16))
            let encryptedString = str.replacingOccurrences(of: iv, with: "",
                                                           options: String.CompareOptions.literal, range: nil) // remove IV

            guard let decryptedString = try? aesDecrypt(encryptedString, key: password, iv: iv) else {
                print("an error occured while decrypting")
                return str
            }
            return decryptedString
        }
        return str
    }



```

**Comment by skreutzberger** [comment]
That would be a breaking change of the functionality without a lot of newly added value to justify it, so we unfortunately can not do it.

**Comment by EliteTechnicalCare** [comment]
What about creating an additional function that would offer this functionality as an alternative to the optional string.
